<a href="https://colab.research.google.com/github/D-Ranaprathap/20221CCS0021/blob/main/basic_op_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
array_3d = np.array([[[1, 2],
                      [3, 4]],
                     [[5, 6],
                      [7, 8]]])
arrays = [array_1d, array_2d, array_3d]
for i, array in enumerate(arrays, start=1):
    print(f"Array {i}:")
    print("Data:")
    print(array)
    print("Shape:", array.shape)
    print("Size:", array.size)
    print("Dimensions:", array.ndim)
    print("Length (for 1D arrays only):", len(array) if array.ndim == 1 else "N/A")
    print()

Array 1:
Data:
[1 2 3 4 5]
Shape: (5,)
Size: 5
Dimensions: 1
Length (for 1D arrays only): 5

Array 2:
Data:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Length (for 1D arrays only): N/A

Array 3:
Data:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Size: 8
Dimensions: 3
Length (for 1D arrays only): N/A



In [4]:
import numpy as np

In [9]:
import random
random_number = random.randint(1, 10)
print("Random number between 1 and 10:", random_number)


Random number between 1 and 10: 5


In [23]:

values = np.linspace(0, 3, num=10)
print("Values:", values)

Values: [0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [22]:
array_ones = np.ones((3, 3))
print("Array filled with ones:")
print(array_ones)

Array filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
array_zeros = np.zeros((3, 3))
print("Array filled with zeros:")
print(array_zeros)

Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
arr_2d = np.array([[1, 2, 3],[4, 4, 6], [7, 8, 3]])
diag_elements = np.diag(arr_2d)
print("Diagonal elements:", diag_elements)

Diagonal elements: [1 4 3]


In [19]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
total_sum = np.sum(arr)
print("Total sum:", total_sum)

Total sum: 21


In [18]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
total_min = np.min(arr)
print("Total minimum value:", total_min)

Total minimum value: 1


In [17]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
total_max = np.max(arr)
print("Total maximum value:", total_max)

Total maximum value: 6


In [16]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_mean = np.mean(arr)
print("Total mean:", total_mean)

Total mean: 3.5


In [15]:
np.random.seed(42)
student_marks = np.random.randint(0, 101, size=50)
passing_marks = student_marks >= 30
num_students_passed = np.sum(passing_marks)
print("Number of students passed:", num_students_passed)
failed_marks = student_marks[student_marks < 30]
print("Failed marks:", failed_marks)

Number of students passed: 36
Failed marks: [14 20 23  2 21  1 29  1 20 21 14  2  6 20]


In [13]:
random_array = np.random.randint(1, 51, size=(5, 5))
print("Random 2D array:")
print(random_array)

Random 2D array:
[[45 32  7 43  1]
 [ 3 18 26  3 24]
 [ 7 26 25  2  5]
 [38 41 39 39 13]
 [47  4 17 38 44]]


In [12]:
odd_numbers = np.arange(-29, 11, 2)
print("Array of odd numbers between -30 and 10:")
print(odd_numbers)

Array of odd numbers between -30 and 10:
[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]


In [25]:
import numpy as np
arr1 = np.arange(5)
print("Example 1:", arr1)
arr2 = np.arange(2, 10)
print("Example 2:", arr2)
arr3 = np.arange(1, 10, 2)
print("Example 3:", arr3)
arr4 = np.arange(0, 1, 0.2)
print("Example 4:", arr4)


Example 1: [0 1 2 3 4]
Example 2: [2 3 4 5 6 7 8 9]
Example 3: [1 3 5 7 9]
Example 4: [0.  0.2 0.4 0.6 0.8]
